export const GET_BUDGET = 'GET_BUDGET';
export const CREATE_BUDGET = 'CREATE_BUDGET';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const DELETE_BUDGET = 'DELETE_BUDGET';

export const GET_FOLDER = 'GET_FOLDER';
export const CREATE_FOLDER = 'CREATE_FOLDER';
export const UPDATE_FOLDER = 'UPDATE FOLDER';
export const DELETE_FOLDER = 'DELETE_FOLDER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_ERRORS = 'GET_ERRORS';